### ISSUE TITLE
Wesbite Inaccessible

### ISSUE THREAD

**Issue by vontell** [m-labs/web#1]
The website seems to be blocked by Chrome and Firefox:

```
The owner of m-labs.hk has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.
```
This has occurred before, but not for extended periods of time. This time I have not been able to get on the site for a couple of hours. (This may be related to the recent DDOS attach on Dyn DNS?)

**Comment by whitequark** [comment]
> This may be related to the recent DDOS attach on Dyn DNS?

It's not. It's an SSL misconfiguration. The cert for CN=serverraum.org is served instead of the one for m-labs.hk.

**Comment by sbourdeauducq** [comment]
Use plain (unencrypted) HTTP in the meantime.

**Comment by whitequark** [comment]
That's not easily possible, because m-labs.hk is sending a `Strict-Transport-Security: max-age=2628000` header. Even if you remove that, everyone who has visited it at least once will not be able to browse the http version until 2628000 seconds pass.

**Comment by sbourdeauducq** [comment]
Fixed.
